# pytorch란?

In [2]:
from __future__ import print_function
import torch

In [3]:
x = torch.rand(5,3)
print(x)

tensor([[0.9047, 0.1219, 0.7599],
        [0.7001, 0.3432, 0.5298],
        [0.9629, 0.2359, 0.4258],
        [0.0836, 0.5833, 0.1934],
        [0.5933, 0.1711, 0.6898]])


In [5]:
x = torch.zeros(5, 3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [8]:
x = x.new_ones(5,3, dtype = torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.1525,  1.2158, -1.1348],
        [ 0.6924,  0.2755,  0.3580],
        [-0.9880,  0.5871, -1.4449],
        [-0.9281,  1.6054, -0.0501],
        [-0.1592, -0.3747, -0.2010]])


In [9]:
print(x.size())

torch.Size([5, 3])


In [12]:
y = torch.rand(5, 3)
print(x+y)

tensor([[-1.0956,  1.4283, -0.4686],
        [ 1.4630,  0.7000,  0.6247],
        [-0.5530,  1.4643, -0.7297],
        [-0.5079,  1.7719,  0.5132],
        [ 0.2840,  0.3927,  0.0447]])


In [13]:
print(torch.add(x,y))

tensor([[-1.0956,  1.4283, -0.4686],
        [ 1.4630,  0.7000,  0.6247],
        [-0.5530,  1.4643, -0.7297],
        [-0.5079,  1.7719,  0.5132],
        [ 0.2840,  0.3927,  0.0447]])


In [14]:
result = torch.zeros(5,3)
torch.add(x, y, out = result)
print(result)

tensor([[-1.0956,  1.4283, -0.4686],
        [ 1.4630,  0.7000,  0.6247],
        [-0.5530,  1.4643, -0.7297],
        [-0.5079,  1.7719,  0.5132],
        [ 0.2840,  0.3927,  0.0447]])


In [15]:
y.add_(x)
print(y)

tensor([[-1.0956,  1.4283, -0.4686],
        [ 1.4630,  0.7000,  0.6247],
        [-0.5530,  1.4643, -0.7297],
        [-0.5079,  1.7719,  0.5132],
        [ 0.2840,  0.3927,  0.0447]])


In [21]:
print(x[0, :])

tensor([-1.1525,  1.2158, -1.1348])


In [25]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 2)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([8, 2])


In [26]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.8349])
0.8348803520202637


# autograd: 자동미분

In [37]:
x = torch.ones(2, 2, requires_grad = True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [38]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [39]:
print(y.grad_fn)

In [40]:
z = y*y*3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [41]:
a = torch.randn(2,2)
a = ((a*3)/(a-1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a*a).sum()
print(b.grad_fn)

False
True


## 변화도(gradient)

In [42]:
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [44]:
x = torch.randn(3, requires_grad = True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2
    
print(y)

tensor([ 867.9766, -990.8374,  478.2767], grad_fn=<MulBackward0>)


In [45]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype = torch.float)
y.backward(v)

print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [48]:
print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


In [49]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)
