# pytorch란?

In [2]:
from __future__ import print_function
import torch

In [3]:
x = torch.rand(5,3)
print(x)

tensor([[0.9047, 0.1219, 0.7599],
        [0.7001, 0.3432, 0.5298],
        [0.9629, 0.2359, 0.4258],
        [0.0836, 0.5833, 0.1934],
        [0.5933, 0.1711, 0.6898]])


In [5]:
x = torch.zeros(5, 3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [8]:
x = x.new_ones(5,3, dtype = torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.1525,  1.2158, -1.1348],
        [ 0.6924,  0.2755,  0.3580],
        [-0.9880,  0.5871, -1.4449],
        [-0.9281,  1.6054, -0.0501],
        [-0.1592, -0.3747, -0.2010]])


In [9]:
print(x.size())

torch.Size([5, 3])


In [12]:
y = torch.rand(5, 3)
print(x+y)

tensor([[-1.0956,  1.4283, -0.4686],
        [ 1.4630,  0.7000,  0.6247],
        [-0.5530,  1.4643, -0.7297],
        [-0.5079,  1.7719,  0.5132],
        [ 0.2840,  0.3927,  0.0447]])


In [13]:
print(torch.add(x,y))

tensor([[-1.0956,  1.4283, -0.4686],
        [ 1.4630,  0.7000,  0.6247],
        [-0.5530,  1.4643, -0.7297],
        [-0.5079,  1.7719,  0.5132],
        [ 0.2840,  0.3927,  0.0447]])


In [14]:
result = torch.zeros(5,3)
torch.add(x, y, out = result)
print(result)

tensor([[-1.0956,  1.4283, -0.4686],
        [ 1.4630,  0.7000,  0.6247],
        [-0.5530,  1.4643, -0.7297],
        [-0.5079,  1.7719,  0.5132],
        [ 0.2840,  0.3927,  0.0447]])


In [15]:
y.add_(x)
print(y)

tensor([[-1.0956,  1.4283, -0.4686],
        [ 1.4630,  0.7000,  0.6247],
        [-0.5530,  1.4643, -0.7297],
        [-0.5079,  1.7719,  0.5132],
        [ 0.2840,  0.3927,  0.0447]])


In [21]:
print(x[0, :])

tensor([-1.1525,  1.2158, -1.1348])


In [25]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 2)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([8, 2])


In [26]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.8349])
0.8348803520202637


# autograd: 자동미분

In [37]:
x = torch.ones(2, 2, requires_grad = True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [38]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [39]:
print(y.grad_fn)

In [40]:
z = y*y*3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [41]:
a = torch.randn(2,2)
a = ((a*3)/(a-1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a*a).sum()
print(b.grad_fn)

False
True


## 변화도(gradient)

In [42]:
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [44]:
x = torch.randn(3, requires_grad = True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2
    
print(y)

tensor([ 867.9766, -990.8374,  478.2767], grad_fn=<MulBackward0>)


In [45]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype = torch.float)
y.backward(v)

print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [48]:
print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


In [49]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)


## 피드 포워드

In [3]:
import torch

def linear(x, W, b):
    y  = torch.mm(x,W) + b
    
    return y

x = torch.FloatTensor(16, 10)
W = torch.FloatTensor(10, 5)
b = torch.FloatTensor(5)
    
y = linear(x, W, b)
print(y)

tensor([[-2.3431e-04, -4.0029e-03, -1.5477e-02,  6.3356e-10, -2.0040e-02],
        [-1.0813e-02, -4.0249e-03, -1.6042e-02,  5.8108e-10, -2.4017e-02],
        [-2.1771e-05, -2.0660e-06,  3.4500e-05,  6.8743e-10, -1.6075e-02],
        [-1.0809e-02, -2.1208e-06,  1.9637e-05,  6.3412e-10, -4.0505e-03],
        [-5.5220e-06, -2.0658e-06,  3.4489e-05,  6.8743e-10, -1.2369e-05],
        [-2.0957e-05, -4.0374e-03,  3.4144e-05,  6.3416e-10, -4.3152e-03],
        [-1.0810e-02, -2.1141e-06, -3.0086e-04,  6.3412e-10, -2.0121e-02],
        [-1.0710e-02, -4.0375e-03, -1.6051e-02,  5.8134e-10, -2.0302e-02],
        [-1.0825e-02, -4.0400e-03, -1.6051e-02,  5.8082e-10, -2.4175e-02],
        [-9.3682e-06, -2.0646e-06, -1.5961e-02,  6.8741e-10, -1.6110e-02],
        [-1.0811e-02, -4.0380e-03,  1.7149e-05,  5.8084e-10, -2.4168e-02],
        [-5.6717e-06, -2.0892e-06,  3.4292e-05,  6.8743e-10, -1.2448e-05],
        [-1.0820e-02, -5.7330e-06, -1.6063e-02,  6.3410e-10, -2.0141e-02],
        [-6.6196e-06, -4.

## nn.Module

In [15]:
import torch
import torch.nn as nn

##앞선 linear함수와 같은 기능을 수행하는 MyLinear 클래스 정의
class MyLinear(nn.Module):
    
    def __init__(self, input_size, output_size):
        super(MyLinear, self).__init__()
        
        self.W = nn.Parameter(torch.FloatTensor(input_size, output_size), requires_grad = True)
        self.b = nn.Parameter(torch.FloatTensor(output_size), requires_grad = True)
    
    def forward(self, x):
        y = torch.mm(x, self.W) + self.b
        
        return y

##MyLinear 클래스 동작 확인
x = torch.FloatTensor(16, 10)
linear = MyLinear(10, 5)
y = linear(x)
print(y)

params = [p.size() for p in linear.parameters()]
print(params)

tensor([[-4.6437e+26, -1.3297e+27,  2.3952e+26, -9.8348e+26,  1.6913e+26],
        [ 3.2593e+27, -3.3565e+27,  5.8095e+27, -9.4354e+27,  6.9115e+27],
        [-2.8420e+26,  1.0367e+26,  6.2490e+24, -6.4245e+25,  3.2971e+26],
        [ 5.9133e+31, -5.5106e+31,  9.6687e+31, -1.5700e+32,  1.1176e+32],
        [-1.0514e+30,  4.1000e+29,  2.6834e+28, -2.4017e+29,  1.2376e+30],
        [-1.8400e+28, -1.8313e+28, -7.5374e+27,  3.0099e+27, -3.5612e+27],
        [-7.1068e+31,  2.2087e+31,  4.3907e+30, -1.4382e+31,  9.0411e+31],
        [-9.9177e+29,  3.8186e+29,  2.7956e+28, -2.2997e+29,  1.1699e+30],
        [-4.2771e+30, -4.3587e+30, -1.7082e+30,  7.4484e+29, -7.3751e+29],
        [ 6.3681e+29,  1.7459e+30,  1.0038e+30,  1.6140e+30, -1.4203e+29],
        [ 9.5310e+33,  2.6892e+33, -1.0282e+34, -1.0185e+34, -1.4059e+33],
        [-1.7706e+31, -1.7622e+31, -7.2529e+30,  2.8962e+30, -3.4268e+30],
        [-1.9627e+27, -2.0614e+28,  1.4071e+27, -2.2309e+28,  1.2786e+28],
        [-4.1883e+27,  1.

더 간단한 버전

In [17]:
import torch
import torch.nn as nn

##앞선 linear함수와 같은 기능을 수행하는 MyLinear 클래스 정의
class MyLinear(nn.Module): #nn.Module을 상속받은 클래스
    
    def __init__(self, input_size, output_size):
        super(MyLinear, self).__init__()
        ##nn.Module의 자식 클래스를 맴버 변수로 가짐
        self.linear = nn.Linear(input_size, output_size)
    
    def forward(self, x):
        y = self.linear(x)
        
        return y

##MyLinear 클래스 동작 확인
x = torch.FloatTensor(16, 10)
linear = MyLinear(10, 5)
y = linear(x)
print(y)

tensor([[ 3.0195e+18, -4.8288e+17, -4.6274e+18, -2.0047e+18, -2.3488e+18],
        [ 3.0609e+02, -6.5847e+00,  7.1624e+01,  2.8257e+02, -5.4590e+01],
        [ 2.3401e+02, -6.4590e+01,  7.7506e+00,  2.4540e+02, -3.5451e+01],
        [ 2.5265e+02, -4.9844e+01,  7.6258e-01,  2.5193e+02, -4.8067e+01],
        [ 3.0612e+02, -3.1937e+01,  2.3304e+01,  3.0251e+02, -6.3974e+01],
        [-1.0855e+19, -1.0054e+19,  1.0857e+19, -6.5665e+18,  1.0358e+19],
        [ 2.3401e+02, -6.4590e+01,  7.7506e+00,  2.4540e+02, -3.5451e+01],
        [ 4.0604e+00, -1.2042e+00,  6.9646e-01,  3.3476e+00, -1.0011e+00],
        [-8.6628e+18,  8.3133e+18, -1.1168e+19,  2.4422e+17,  6.4443e+18],
        [ 2.3401e+02, -6.4590e+01,  7.7506e+00,  2.4540e+02, -3.5451e+01],
        [ 7.8352e+18,  1.0537e+19, -6.2298e+18,  8.5712e+18, -8.0092e+18],
        [ 3.0195e+18, -4.8288e+17, -4.6274e+18, -2.0047e+18, -2.3488e+18],
        [ 3.0609e+02, -6.5847e+00,  7.1624e+01,  2.8257e+02, -5.4590e+01],
        [ 2.8725e+02, -5.

## 역전파 수행

In [24]:
objective = 100

x = torch.FloatTensor(16, 10)
linear = MyLinear(10, 5)
y = linear(x)
loss = (objective - y.sum())*2

loss.backward()
print(loss)

tensor(-1.7433e+35, grad_fn=<MulBackward0>)


## train()과 eval()

In [25]:
##학습 모드 -> 추론 모드
linear.eval()

##추론 모드 -> 학습 모드
linear.train()

MyLinear(
  (linear): Linear(in_features=10, out_features=5, bias=True)
)

## 선형회귀분석 예제

1. 임의로 생성한 텐서들을
2. 근사하고자 하는 정답 함수에 넣어 정답(y)를 구하고
3. 그 정답고 신경망을 통과한 y'과의 차이를 평균제곱오차(MSE)를 통해 구하여
4. 확률적 경사하강법(SGD)를 통해 최적화하기

In [34]:
## 1개의 선형 계층을 가진 My Model 모듈 생성
import random

import torch
import torch.nn as nn

class MyModel(nn.Module):
    
    def __init__(self, input_size, output_size):
        super(MyModel, self).__init__()
        
        self.linear = nn.Linear(input_size, output_size)
    
    def forward(self, x):
        y = self.linear(x)
        
        return y

## 손실함수를 최소로 만드는 파라미터를 찾는 함수
def ground_truth(x):
    return 3 * x[:, 0] + x[:, 1] - 2 * x[:, 2]

## 순전파, 역전파를 이용해 신경망을 학습시키는 함수
def train(model, x, y, optim):
    
    optim.zero_grad()
    
    #순전파
    y_hat = model(x)
    
    #추론과 실제 값의 오차 구하기
    loss = ((y - y_hat)**2).sum()/x.size(0)
    
    #역전파
    loss.backward()
    
    #경사하강법 1회
    optim.step()
    
    return loss.data


하이퍼파라미터 설정하기

In [35]:
batch_size = 1
n_epochs = 1000
n_iter = 10000

model = MyModel(3, 1)
optim = torch.optim.SGD(model.parameters(), lr =0.0001, momentum=0.1)

print(model)

MyModel(
  (linear): Linear(in_features=3, out_features=1, bias=True)
)


평균 손실값이 0.001보다 작아질 때까지 훈련시키기

In [37]:
for epoch in range(n_epochs):
    avg_loss = 0
    
    for i in range(n_iter):
        x = torch.rand(batch_size, 3)
        y = ground_truth(x.data)
        
        loss = train(model, x, y ,optim)
        
        avg_loss +=loss
        avg_loss = avg_loss/n_iter
    
    x_valid = torch.FloatTensor([[.3, .2, .1]])
    y_valid = ground_truth(x_valid.data)
    
    model.eval()
    y_hat = model(x_valid)
    model.train()
    
    print(avg_loss, y_valid.data[0], y_hat.data[0, 0])
    
    if avg_loss < .001:
        break

tensor(2.2635e-05) tensor(0.9000) tensor(0.8657)
